AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Cloud Intelligence Dashboards Framework'

Parameters:
  QuickSightUser:
    Type: String
    Description: QuickSight user ARN
  S3BucketName:
    Type: String
    Description: S3 bucket for data storage

Resources:
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  QuickSightDataSource:
    Type: AWS::QuickSight::DataSource
    Properties:
      DataSourceId: cloud-intelligence-datasource
      Name: Cloud Intelligence Data Source
      AwsAccountId: !Ref AWS::AccountId
      Type: S3

Outputs:
  BucketName:
    Value: !Ref DataBucket
  DataSourceId:
    Value: !Ref QuickSightDataSource